# Generated by Django 4.1.6 on 2023-04-28 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_semister_student_alter_semister_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semister',
            name='student',
            field=models.ManyToManyField(to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='semister',
            name='subject',
            field=models.ManyToManyField(to='student_app.subject'),
        ),
        migrations.AlterField(
            model_name='semister',
            name='teacher',
            field=models.ManyToManyField(to='student_app.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
