# Generated by Django 4.1.6 on 2023-05-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_semister_student_alter_semister_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('admin', 'ADMIN')], default='student', max_length=100),
        ),
    ]
