# Generated by Django 4.1.6 on 2023-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_user_is_admin_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semister',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='semister',
            name='student',
            field=models.ManyToManyField(to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='semister',
            name='subject',
            field=models.ManyToManyField(to='student_app.subject'),
        ),
        migrations.AlterField(
            model_name='semister',
            name='teacher',
            field=models.ManyToManyField(to='student_app.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='semister',
            field=models.ManyToManyField(to='student_app.semister'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='student_app.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='student_app.teacher'),
        ),
    ]
