# Generated by Django 4.1.6 on 2023-05-01 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_remove_post_user_remove_course_semister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionmessage',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionmessage',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
